// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: applyJobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const applyJobs = `-- name: ApplyJobs :one
INSERT INTO applications (id, applicant_id, job_id, resume_url, status)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, applicant_id, job_id, resume_url, status
`

type ApplyJobsParams struct {
	ApplicantID uuid.UUID
	JobID       uuid.UUID
	ResumeUrl   string
	Status      string
}

func (q *Queries) ApplyJobs(ctx context.Context, arg ApplyJobsParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, applyJobs,
		arg.ApplicantID,
		arg.JobID,
		arg.ResumeUrl,
		arg.Status,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ApplicantID,
		&i.JobID,
		&i.ResumeUrl,
		&i.Status,
	)
	return i, err
}
