// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: createJobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createJobs = `-- name: CreateJobs :one
INSERT INTO jobs (id, created_at, updated_at, title, description, location, type, salary, employer_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5, 
    $6
)
RETURNING id, created_at, updated_at, title, description, location, type, salary, employer_id
`

type CreateJobsParams struct {
	Title       string
	Description string
	Location    string
	Type        string
	Salary      float32
	EmployerID  uuid.UUID
}

func (q *Queries) CreateJobs(ctx context.Context, arg CreateJobsParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJobs,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Type,
		arg.Salary,
		arg.EmployerID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Type,
		&i.Salary,
		&i.EmployerID,
	)
	return i, err
}
