// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deleteJobByID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteJobByID = `-- name: DeleteJobByID :one
DELETE FROM jobs
WHERE 
    id = $1
    AND employer_id = $2
RETURNING id
`

type DeleteJobByIDParams struct {
	ID         uuid.UUID
	EmployerID uuid.UUID
}

func (q *Queries) DeleteJobByID(ctx context.Context, arg DeleteJobByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteJobByID, arg.ID, arg.EmployerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
