// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deleteApplication.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAppByID = `-- name: DeleteAppByID :one
DELETE FROM applications
WHERE 
    id = $1
    AND applicant_id = $2
RETURNING id
`

type DeleteAppByIDParams struct {
	ID          uuid.UUID
	ApplicantID uuid.UUID
}

func (q *Queries) DeleteAppByID(ctx context.Context, arg DeleteAppByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteAppByID, arg.ID, arg.ApplicantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
