// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: filterJob.sql

package database

import (
	"context"
	"database/sql"
)

const filtersJobs = `-- name: FiltersJobs :many
SELECT id, created_at, updated_at, title, description, location, type, salary, employer_id
FROM jobs
WHERE
    location ILIKE '%' || $1 || '%'
    AND ($2 = '' OR type = $2)
    AND ($3 = 1 OR salary >= $3)
    AND ($4 = 1 OR salary <= $4)
ORDER BY created_at DESC
`

type FiltersJobsParams struct {
	Column1 sql.NullString
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
}

func (q *Queries) FiltersJobs(ctx context.Context, arg FiltersJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, filtersJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Type,
			&i.Salary,
			&i.EmployerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
