// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getApplyJobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getApplyJobs = `-- name: GetApplyJobs :one
SELECT id, applicant_id, job_id, resume_url, status FROM applications
WHERE id = $1
`

func (q *Queries) GetApplyJobs(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplyJobs, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ApplicantID,
		&i.JobID,
		&i.ResumeUrl,
		&i.Status,
	)
	return i, err
}
