// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getAppsByJobID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getApplyByJobID = `-- name: GetApplyByJobID :many
SELECT id, applicant_id, job_id, resume_url, status FROM applications
WHERE job_id = $1
`

func (q *Queries) GetApplyByJobID(ctx context.Context, jobID uuid.UUID) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getApplyByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.ApplicantID,
			&i.JobID,
			&i.ResumeUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
