// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getJobByID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getJobsByID = `-- name: GetJobsByID :one
SELECT id, title, description, location, type, salary, employer_id FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobsByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobsByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Type,
		&i.Salary,
		&i.EmployerID,
	)
	return i, err
}
