// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: searchJob.sql

package database

import (
	"context"
	"database/sql"
)

const searchJobs = `-- name: SearchJobs :many
SELECT id, created_at, updated_at, title, description, location, type, salary, employer_id
FROM jobs
WHERE title ILIKE '%' || $1 || '%'
   OR description ILIKE '%' || $1 || '%'
`

func (q *Queries) SearchJobs(ctx context.Context, dollar_1 sql.NullString) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, searchJobs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Type,
			&i.Salary,
			&i.EmployerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
