// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateApplyJobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateApplyJob = `-- name: UpdateApplyJob :exec
UPDATE applications
SET 
    resume_url = $1
WHERE
    id = $2
`

type UpdateApplyJobParams struct {
	ResumeUrl string
	ID        uuid.UUID
}

func (q *Queries) UpdateApplyJob(ctx context.Context, arg UpdateApplyJobParams) error {
	_, err := q.db.ExecContext(ctx, updateApplyJob, arg.ResumeUrl, arg.ID)
	return err
}
