// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateRefreshTokens.sql

package database

import (
	"context"
)

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET
    revoked_at = now(),
    updated_at = now()
WHERE
    token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
