// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateJob.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET 
    title = $1,
    updated_at = NOW(),
    description = $2, 
    location = $3,
    type = $4, 
    salary = $5

WHERE
    id = $6
`

type UpdateJobParams struct {
	Title       string
	Description string
	Location    string
	Type        string
	Salary      float32
	ID          uuid.UUID
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Type,
		arg.Salary,
		arg.ID,
	)
	return err
}
